easy_admin:
  user:
    display_name: true
    display_avatar: false
    name_property_path: 'email'
  entities:
    # List the entity class name you want to manage
    Page:
      class: App\Entity\Page
    User:
      class: App\Entity\User
      form:
        fields:
          - { property: 'email' }
          - { property: 'password' }
          - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'User': 'ROLE_USER', 'Admin': 'ROLE_ADMIN' } } }
